// 多语言系统
class LanguageSystem {
    constructor() {
        this.currentLang = localStorage.getItem('selectedLanguage') || 'zh-CN';
        this.translations = {};
        this.init();
    }
    
    async init() {
        await this.loadTranslations();
        this.applyLanguage(this.currentLang);
        this.setupLanguageSelector();
    }
    
    async loadTranslations() {
        this.translations = {
            'zh-CN': {
                // 通用导航
                'home': '首页',
                'about': '关于我们',
                'products': '产品中心',
                'blog': '博客',
                'contact': '联系我们',
                
                // 产品分类
                'fuel-dispenser': '加油机',
                'fuel-dispenser-parts': '加油机配件',
                'adblue-equipment': '尿素配件',
                'industrial-pump': '工业泵和流量计',
                'lpg-equipment': 'LPG 配件',
                'other-equipment': '其他',
                
                // 购物车
                'shopping-cart': '购物车',
                'request-quotation': '请求报价',
                'add-to-cart': '添加到购物车',
                
                // 首页内容
                'hero-title1': '专业工业设备供应商',
                'hero-desc1': '提供高质量加油机、工业泵和流量计等设备',
                'hero-title2': '优质加油机解决方案',
                'hero-desc2': '提供各种型号的加油机及配件',
                'hero-title3': '工业泵与流量计专家',
                'hero-desc3': '专业的工业泵和流量计供应商',
                'view-products': '查看产品',
                'hot-products': '热销产品',
                'product-categories': '产品分类',
                'featured-products': '推荐产品',
                'our-advantages': '我们的优势',
                'high-quality': '高质量',
                'quality-desc': '我们提供符合国际标准的高质量产品',
                'professional-service': '专业服务',
                'service-desc': '专业的售前咨询和售后服务团队',
                'fast-delivery': '快速交付',
                'delivery-desc': '高效的物流体系确保快速交付',
                'technical-support': '技术支持',
                'support-desc': '提供全面的技术支持和解决方案',
                
                // LC型流量计推荐
                'lc-flowmeter-title': 'LC型流量计',
                'lc-flowmeter-desc': '高精度LC型流量计，适用于各种工业流体测量。采用先进技术，确保测量准确性和稳定性。',
                'feature1': '高精度测量',
                'feature2': '耐腐蚀材料',
                'feature3': '易于安装维护',
                'feature4': '多种规格可选',
                'urgent-delivery': '交期紧张',
                'delivery-warning': '⚠️ 交期紧张，建议提前预订',
                'view-details': '查看详情',
                
                // 页脚
                'contact-info': '联系信息',
                'company-name1': '连云港路扬配件有限公司 LUIANG PARTS LIANYUNGANG CO.,LTD',
                'address1': '地址: 江苏省灌云县义凡广场1号楼 222200',
                'company-name2': '路扬配件有限公司 LUIANG PARTS CO.,LTD',
                'address2': '地址: 上海市灵山路958号5号楼',
                'quick-links': '快速链接',
                'all-rights-reserved': '版权所有',
                
                // 产品页面
                'products-desc': '探索我们的高质量工业设备产品线',
                'filter-by-category': '按分类筛选:',
                'all-categories': '所有分类',
                'sort-by': '排序方式:',
                'sort-name': '按名称',
                'sort-price-low': '价格从低到高',
                'sort-price-high': '价格从高到低',
                'load-more': '加载更多',
                'need-help': '需要产品帮助？',
                'inquiry-desc': '我们的专家团队随时为您提供专业的产品咨询和技术支持',
                'contact-expert': '联系专家',
                
                // 产品详情页面
                'sku': '产品编号:',
                'in-stock': '有库存',
                'product-features': '产品特点',
                'specifications': '技术规格',
                'quantity': '数量:',
                'request-quote': '请求报价',
                'delivery-time': '预计交货时间: 2-4周',
                'product-description': '产品描述',
                'detailed-specs': '详细规格',
                'applications': '应用领域',
                'downloads': '资料下载',
                'product-overview': '产品概述',
                'key-features': '主要特点',
                'technical-specs': '技术规格',
                'application-areas': '应用领域',
                'download-resources': '下载资源',
                'related-products': '相关产品',
                'feature-high-precision': '高精度测量，误差小于±0.5%',
                'feature-corrosion-resistant': '耐腐蚀材料，使用寿命长',
                'feature-easy-installation': '易于安装和维护',
                'feature-multiple-specs': '多种规格可选，满足不同需求',
                'spec-material': '材质',
                'spec-accuracy': '精度',
                'spec-pressure': '工作压力',
                'spec-temperature': '工作温度',
                'spec-model': '型号',
                'spec-measurement': '测量范围',
                'spec-accuracy': '精度等级',
                'spec-pressure-rating': '压力等级',
                'spec-parameter': '参数',
                'spec-value': '数值',
                'feature1-detail': '高精度测量，满足严格的工业标准',
                'feature2-detail': '宽量程比，适应不同流量范围',
                'feature3-detail': '多种输出信号可选',
                'feature4-detail': 'IP67防护等级，适合恶劣环境',
                'app-petrochemical': '石油化工行业',
                'app-water-treatment': '水处理系统',
                'app-food-beverage': '食品饮料行业',
                'app-pharmaceutical': '制药行业',
                'app-chemical': '化学工业',
                'download-catalog': '产品手册下载',
                'download-certificate': '认证证书下载',
                'download-manual': '安装手册下载',
                
                // 关于我们页面
                'about-us': '关于我们',
                'about-desc': '专业工业设备供应商，致力于为客户提供优质产品和服务',
                'welcome-to-luiang': '欢迎来到 LUIANG MACHINE',
                'company-intro-1': '连云港路扬配件有限公司是一家专业的工业设备供应商，专注于加油机、工业泵、流量计及相关配件的研发、生产和销售。',
                'company-intro-2': '我们拥有多年的行业经验，致力于为全球客户提供高质量、可靠的工业设备解决方案。我们的产品广泛应用于石油化工、水处理、食品饮料等多个行业。',
                'company-intro-3': '通过持续的技术创新和严格的质量控制，我们确保每一件产品都符合国际标准，满足客户的多样化需求。',
                'company-building-alt': '公司建筑',
                'our-journey': '我们的历程',
                'timeline-2010-title': '公司成立',
                'timeline-2010-desc': '在连云港成立，开始专注于工业设备贸易',
                'timeline-2015-title': '业务扩展',
                'timeline-2015-desc': '在上海设立分公司，扩大业务范围',
                'timeline-2018-title': '产品升级',
                'timeline-2018-desc': '引进先进生产线，提升产品质量',
                'timeline-2023-title': '国际化发展',
                'timeline-2023-desc': '产品出口至多个国家，建立国际合作关系',
                'our-values': '我们的价值观',
                'value-quality': '质量第一',
                'value-quality-desc': '我们始终坚持质量至上的原则，确保每一件产品都达到最高标准',
                'value-innovation': '持续创新',
                'value-innovation-desc': '不断研发新技术，推出满足市场需求的新产品',
                'value-customer': '客户至上',
                'value-customer-desc': '以客户需求为导向，提供个性化的解决方案',
                'value-integrity': '诚信经营',
                'value-integrity-desc': '坚持诚信原则，建立长期稳定的合作关系',
                'our-team': '我们的团队',
                'team-member-1': '张工',
                'position-1': '技术总监',
                'member-desc-1': '15年工业设备经验，专注于产品研发和技术创新',
                'team-member-2': '李经理',
                'position-2': '销售经理',
                'member-desc-2': '10年国际贸易经验，精通多国语言',
                'team-member-3': '王主管',
                'position-3': '客服主管',
                'member-desc-3': '8年客户服务经验，提供专业的技术支持',
                'certifications': '资质证书',
                'cert-iso': 'ISO9001质量体系认证',
                'cert-ce': 'CE认证',
                'cert-patent': '多项产品专利证书',
                
                // 博客页面
                'blog': '博客',
                'blog-desc': '行业资讯、技术文章和公司动态',
                'post-date': '发布日期',
                'category-technical': '技术文章',
                'category-technology': '技术前沿',
                'category-news': '公司动态',
                'category-guide': '选购指南',
                'blog-title-1': '工业泵的日常维护与保养指南',
                'blog-excerpt-1': '工业泵作为重要的工业设备，正确的维护保养可以显著延长其使用寿命。本文详细介绍工业泵的日常检查、定期维护和常见故障处理方法...',
                'blog-title-2': '流量计技术的最新发展趋势',
                'blog-excerpt-2': '随着工业4.0的发展，流量计技术也在不断创新。智能流量计、无线传输、大数据分析等新技术正在改变传统的流量测量方式...',
                'blog-title-3': 'LUIANG MACHINE 参加2024国际工业设备展',
                'blog-excerpt-3': '我们很荣幸参加2024年国际工业设备展览会，展示了最新的LC型流量计和智能加油机解决方案，获得了众多客户的关注和好评...',
                'blog-title-4': '如何选择合适的工业流量计',
                'blog-excerpt-4': '选择适合的工业流量计需要考虑多个因素，包括介质特性、流量范围、精度要求、安装环境等。本文为您提供详细的选购指南...',
                'read-more': '阅读更多',
                'search-blog': '搜索博客',
                'search-placeholder': '输入关键词...',
                'search': '搜索',
                'categories': '分类',
                'category-all': '全部文章',
                'popular-posts': '热门文章',
                'popular-post-1': '工业泵常见故障及解决方法',
                'popular-post-2': '流量计安装注意事项',
                'popular-post-3': '加油机维护保养周期',
                'tags': '标签',
                'tag-pump': '工业泵',
                'tag-flowmeter': '流量计',
                'tag-dispenser': '加油机',
                'tag-maintenance': '维护保养',
                'tag-technology': '技术',
                'tag-installation': '安装',
                'next-page': '下一页',
                
                // 联系页面
                'contact-us': '联系我们',
                'contact-desc': '我们随时为您提供专业的咨询和服务',
                'phone': '电话',
                'email': '邮箱',
                'send-message': '发送消息',
                'form-name': '姓名 *',
                'form-company': '公司名称',
                'form-email': '邮箱 *',
                'form-phone': '电话',
                'form-subject': '主题 *',
                'form-message': '消息内容 *',
                'select-subject': '选择咨询主题',
                'subject-product': '产品咨询',
                'subject-quotation': '报价请求',
                'subject-technical': '技术支持',
                'subject-partnership': '合作咨询',
                'subject-other': '其他',
                'message-placeholder': '请详细描述您的需求...',
                'our-location': '我们的位置',
                'map-loading': '地图加载中...',
                'map-desc': '连云港路扬配件有限公司位置',
                'visit-us': '来访指南',
                'visit-desc': '欢迎您前来参观考察，我们提供专业的设备展示和技术讲解服务。',
                'business-hours': '营业时间',
                'hours-weekdays': '周一至周五: 8:30-17:30',
                'hours-saturday': '周六: 9:00-12:00',
                'hours-sunday': '周日: 休息',
                'faq': '常见问题',
                'faq-1-question': '如何获取产品报价？',
                'faq-1-answer': '您可以通过联系我们页面提交询价请求，或直接发送邮件至luiangparts@luiangparts.com，我们会尽快为您提供详细报价。',
                'faq-2-question': '产品交货期是多久？',
                'faq-2-answer': '标准产品交货期为2-4周，具体时间根据产品型号和订单数量确定。紧急订单可协商加急处理。',
                'faq-3-question': '是否提供技术支持？',
                'faq-3-answer': '是的，我们提供全面的技术支持服务，包括产品安装指导、使用培训和故障排除等。',
                'faq-4-question': '支持哪些支付方式？',
                'faq-4-answer': '我们支持TT电汇、信用证等多种支付方式，具体可根据客户需求协商确定。',
                
                // 页面标题
                'page-title-home': 'LUIANG MACHINE - 专业工业设备供应商',
                'page-title-products': '产品中心 - LUIANG MACHINE',
                'page-title-about': '关于我们 - LUIANG MACHINE',
                'page-title-blog': '博客 - LUIANG MACHINE',
                'page-title-contact': '联系我们 - LUIANG MACHINE'
            },
            'en': {
                // 通用导航
                'home': 'Home',
                'about': 'About Us',
                'products': 'Products',
                'blog': 'Blog',
                'contact': 'Contact',
                
                // 产品分类
                'fuel-dispenser': 'Fuel Dispenser',
                'fuel-dispenser-parts': 'Fuel Dispenser Parts',
                'adblue-equipment': 'Adblue Equipment',
                'industrial-pump': 'Industrial Pump & Flowmeter',
                'lpg-equipment': 'LPG Equipment',
                'other-equipment': 'Other Equipment',
                
                // 购物车
                'shopping-cart': 'Shopping Cart',
                'request-quotation': 'Request Quotation',
                'add-to-cart': 'Add to Cart',
                
                // 首页内容
                'hero-title1': 'Professional Industrial Equipment Supplier',
                'hero-desc1': 'Providing high-quality fuel dispensers, industrial pumps and flowmeters',
                'hero-title2': 'Premium Fuel Dispenser Solutions',
                'hero-desc2': 'Offering various models of fuel dispensers and accessories',
                'hero-title3': 'Industrial Pump & Flowmeter Experts',
                'hero-desc3': 'Professional supplier of industrial pumps and flowmeters',
                'view-products': 'View Products',
                'hot-products': 'Hot Products',
                'product-categories': 'Product Categories',
                'featured-products': 'Featured Products',
                'our-advantages': 'Our Advantages',
                'high-quality': 'High Quality',
                'quality-desc': 'We provide high-quality products that meet international standards',
                'professional-service': 'Professional Service',
                'service-desc': 'Professional pre-sales consultation and after-sales service team',
                'fast-delivery': 'Fast Delivery',
                'delivery-desc': 'Efficient logistics system ensures fast delivery',
                'technical-support': 'Technical Support',
                'support-desc': 'Comprehensive technical support and solutions',
                
                // LC型流量计推荐
                'lc-flowmeter-title': 'LC Type Flowmeter',
                'lc-flowmeter-desc': 'High-precision LC type flowmeter, suitable for various industrial fluid measurements. Using advanced technology to ensure measurement accuracy and stability.',
                'feature1': 'High Precision Measurement',
                'feature2': 'Corrosion Resistant Material',
                'feature3': 'Easy Installation & Maintenance',
                'feature4': 'Multiple Specifications Available',
                'urgent-delivery': 'Urgent Delivery',
                'delivery-warning': '⚠️ Urgent delivery, recommend early booking',
                'view-details': 'View Details',
                
                // 页脚
                'contact-info': 'Contact Information',
                'company-name1': 'LUIANG PARTS LIANYUNGANG CO.,LTD',
                'address1': 'Add: #1 Building Yifan Plaza Guanyun County Jiangsu China.222200',
                'company-name2': 'LUIANG PARTS CO.,LTD',
                'address2': 'Add: 5th Building, No 958 Rd Lingshan Shanghai China',
                'quick-links': 'Quick Links',
                'all-rights-reserved': 'All Rights Reserved',
                
                // 产品页面
                'products-desc': 'Explore our high-quality industrial equipment product lines',
                'filter-by-category': 'Filter by Category:',
                'all-categories': 'All Categories',
                'sort-by': 'Sort by:',
                'sort-name': 'By Name',
                'sort-price-low': 'Price: Low to High',
                'sort-price-high': 'Price: High to Low',
                'load-more': 'Load More',
                'need-help': 'Need Product Help?',
                'inquiry-desc': 'Our expert team is ready to provide professional product consultation and technical support',
                'contact-expert': 'Contact Expert',
                
                // 产品详情页面
                'sku': 'SKU:',
                'in-stock': 'In Stock',
                'product-features': 'Product Features',
                'specifications': 'Specifications',
                'quantity': 'Quantity:',
                'request-quote': 'Request Quote',
                'delivery-time': 'Estimated Delivery: 2-4 weeks',
                'product-description': 'Product Description',
                'detailed-specs': 'Detailed Specifications',
                'applications': 'Applications',
                'downloads': 'Downloads',
                'product-overview': 'Product Overview',
                'key-features': 'Key Features',
                'technical-specs': 'Technical Specifications',
                'application-areas': 'Application Areas',
                'download-resources': 'Download Resources',
                'related-products': 'Related Products',
                'feature-high-precision': 'High precision measurement, error less than ±0.5%',
                'feature-corrosion-resistant': 'Corrosion resistant material, long service life',
                'feature-easy-installation': 'Easy installation and maintenance',
                'feature-multiple-specs': 'Multiple specifications available to meet different needs',
                'spec-material': 'Material',
                'spec-accuracy': 'Accuracy',
                'spec-pressure': 'Working Pressure',
                'spec-temperature': 'Working Temperature',
                'spec-model': 'Model',
                'spec-measurement': 'Measurement Range',
                'spec-accuracy': 'Accuracy Class',
                'spec-pressure-rating': 'Pressure Rating',
                'spec-parameter': 'Parameter',
                'spec-value': 'Value',
                'feature1-detail': 'High precision measurement, meets strict industrial standards',
                'feature2-detail': 'Wide range ratio, adapts to different flow ranges',
                'feature3-detail': 'Multiple output signals available',
                'feature4-detail': 'IP67 protection grade, suitable for harsh environments',
                'app-petrochemical': 'Petrochemical Industry',
                'app-water-treatment': 'Water Treatment Systems',
                'app-food-beverage': 'Food & Beverage Industry',
                'app-pharmaceutical': 'Pharmaceutical Industry',
                'app-chemical': 'Chemical Industry',
                'download-catalog': 'Product Catalog Download',
                'download-certificate': 'Certification Download',
                'download-manual': 'Installation Manual Download',
                
                // 关于我们页面
                'about-us': 'About Us',
                'about-desc': 'Professional industrial equipment supplier committed to providing quality products and services',
                'welcome-to-luiang': 'Welcome to LUIANG MACHINE',
                'company-intro-1': 'LUIANG PARTS LIANYUNGANG CO.,LTD is a professional industrial equipment supplier, focusing on the R&D, production and sales of fuel dispensers, industrial pumps, flowmeters and related accessories.',
                'company-intro-2': 'With years of industry experience, we are committed to providing global customers with high-quality, reliable industrial equipment solutions. Our products are widely used in petrochemical, water treatment, food and beverage and other industries.',
                'company-intro-3': 'Through continuous technological innovation and strict quality control, we ensure that every product meets international standards and satisfies diverse customer needs.',
                'company-building-alt': 'Company Building',
                'our-journey': 'Our Journey',
                'timeline-2010-title': 'Company Founded',
                'timeline-2010-desc': 'Established in Lianyungang, began focusing on industrial equipment trade',
                'timeline-2015-title': 'Business Expansion',
                'timeline-2015-desc': 'Set up branch in Shanghai to expand business scope',
                'timeline-2018-title': 'Product Upgrade',
                'timeline-2018-desc': 'Introduced advanced production lines to improve product quality',
                'timeline-2023-title': 'International Development',
                'timeline-2023-desc': 'Products exported to multiple countries, established international partnerships',
                'our-values': 'Our Values',
                'value-quality': 'Quality First',
                'value-quality-desc': 'We always adhere to the principle of quality first, ensuring every product meets the highest standards',
                'value-innovation': 'Continuous Innovation',
                'value-innovation-desc': 'Continuously develop new technologies and launch new products that meet market demands',
                'value-customer': 'Customer First',
                'value-customer-desc': 'Customer demand-oriented, providing personalized solutions',
                'value-integrity': 'Integrity Operation',
                'value-integrity-desc': 'Adhere to integrity principles and establish long-term stable cooperative relationships',
                'our-team': 'Our Team',
                'team-member-1': 'Zhang Engineer',
                'position-1': 'Technical Director',
                'member-desc-1': '15 years of industrial equipment experience, focusing on product R&D and technological innovation',
                'team-member-2': 'Li Manager',
                'position-2': 'Sales Manager',
                'member-desc-2': '10 years of international trade experience, proficient in multiple languages',
                'team-member-3': 'Wang Supervisor',
                'position-3': 'Customer Service Supervisor',
                'member-desc-3': '8 years of customer service experience, providing professional technical support',
                'certifications': 'Certifications',
                'cert-iso': 'ISO9001 Quality System Certification',
                'cert-ce': 'CE Certification',
                'cert-patent': 'Multiple Product Patent Certificates',
                
                // 博客页面
                'blog': 'Blog',
                'blog-desc': 'Industry news, technical articles and company updates',
                'post-date': 'Post Date',
                'category-technical': 'Technical Articles',
                'category-technology': 'Technology Frontier',
                'category-news': 'Company News',
                'category-guide': 'Buying Guide',
                'blog-title-1': 'Daily Maintenance and Care Guide for Industrial Pumps',
                'blog-excerpt-1': 'Industrial pumps are important industrial equipment, proper maintenance can significantly extend their service life. This article details daily inspection, regular maintenance and common troubleshooting methods...',
                'blog-title-2': 'Latest Development Trends in Flowmeter Technology',
                'blog-excerpt-2': 'With the development of Industry 4.0, flowmeter technology is also constantly innovating. New technologies such as smart flowmeters, wireless transmission, and big data analysis are changing traditional flow measurement methods...',
                'blog-title-3': 'LUIANG MACHINE Participates in 2024 International Industrial Equipment Exhibition',
                'blog-excerpt-3': 'We are honored to participate in the 2024 International Industrial Equipment Exhibition, showcasing the latest LC type flowmeters and smart fuel dispenser solutions, receiving attention and praise from many customers...',
                'blog-title-4': 'How to Choose the Right Industrial Flowmeter',
                'blog-excerpt-4': 'Choosing the right industrial flowmeter requires considering multiple factors, including medium characteristics, flow range, accuracy requirements, installation environment, etc. This article provides a detailed buying guide...',
                'read-more': 'Read More',
                'search-blog': 'Search Blog',
                'search-placeholder': 'Enter keywords...',
                'search': 'Search',
                'categories': 'Categories',
                'category-all': 'All Articles',
                'popular-posts': 'Popular Posts',
                'popular-post-1': 'Common Industrial Pump Failures and Solutions',
                'popular-post-2': 'Flowmeter Installation Considerations',
                'popular-post-3': 'Fuel Dispenser Maintenance Schedule',
                'tags': 'Tags',
                'tag-pump': 'Industrial Pump',
                'tag-flowmeter': 'Flowmeter',
                'tag-dispenser': 'Fuel Dispenser',
                'tag-maintenance': 'Maintenance',
                'tag-technology': 'Technology',
                'tag-installation': 'Installation',
                'next-page': 'Next Page',
                
                // 联系页面
                'contact-us': 'Contact Us',
                'contact-desc': 'We are always here to provide professional consultation and service',
                'phone': 'Phone',
                'email': 'Email',
                'send-message': 'Send Message',
                'form-name': 'Name *',
                'form-company': 'Company Name',
                'form-email': 'Email *',
                'form-phone': 'Phone',
                'form-subject': 'Subject *',
                'form-message': 'Message Content *',
                'select-subject': 'Select Inquiry Subject',
                'subject-product': 'Product Inquiry',
                'subject-quotation': 'Quotation Request',
                'subject-technical': 'Technical Support',
                'subject-partnership': 'Partnership Inquiry',
                'subject-other': 'Other',
                'message-placeholder': 'Please describe your needs in detail...',
                'our-location': 'Our Location',
                'map-loading': 'Map Loading...',
                'map-desc': 'LUIANG PARTS LIANYUNGANG CO.,LTD Location',
                'visit-us': 'Visit Guide',
                'visit-desc': 'Welcome to visit and inspect, we provide professional equipment display and technical explanation services.',
                'business-hours': 'Business Hours',
                'hours-weekdays': 'Monday-Friday: 8:30-17:30',
                'hours-saturday': 'Saturday: 9:00-12:00',
                'hours-sunday': 'Sunday: Closed',
                'faq': 'FAQ',
                'faq-1-question': 'How to get product quotation?',
                'faq-1-answer': 'You can submit an inquiry request through our contact page, or send an email directly to luiangparts@luiangparts.com, we will provide you with a detailed quotation as soon as possible.',
                'faq-2-question': 'What is the product delivery time?',
                'faq-2-answer': 'Standard product delivery time is 2-4 weeks, specific time depends on product model and order quantity. Urgent orders can be negotiated for expedited processing.',
                'faq-3-question': 'Do you provide technical support?',
                'faq-3-answer': 'Yes, we provide comprehensive technical support services, including product installation guidance, usage training and troubleshooting.',
                'faq-4-question': 'What payment methods are supported?',
                'faq-4-answer': 'We support TT wire transfer, letter of credit and other payment methods, specific can be negotiated according to customer needs.',
                
                // 页面标题
                'page-title-home': 'LUIANG MACHINE - Professional Industrial Equipment Supplier',
                'page-title-products': 'Products - LUIANG MACHINE',
                'page-title-about': 'About Us - LUIANG MACHINE',
                'page-title-blog': 'Blog - LUIANG MACHINE',
                'page-title-contact': 'Contact - LUIANG MACHINE'
            },
            'ru': {
                // 通用导航
                'home': 'Главная',
                'about': 'О нас',
                'products': 'Продукты',
                'blog': 'Блог',
                'contact': 'Контакты',
                
                // 产品分类
                'fuel-dispenser': 'Топливораздаточная колонка',
                'fuel-dispenser-parts': 'Запчасти для ТРК',
                'adblue-equipment': 'Оборудование Adblue',
                'industrial-pump': 'Промышленные насосы и расходомеры',
                'lpg-equipment': 'Оборудование для СУГ',
                'other-equipment': 'Другое оборудование',
                
                // 购物车
                'shopping-cart': 'Корзина',
                'request-quotation': 'Запрос цены',
                'add-to-cart': 'Добавить в корзину',
                
                // 首页内容
                'hero-title1': 'Профессиональный поставщик промышленного оборудования',
                'hero-desc1': 'Предоставляем высококачественные топливораздаточные колонки, промышленные насосы и расходомеры',
                'hero-title2': 'Премиальные решения для ТРК',
                'hero-desc2': 'Предлагаем различные модели топливораздаточных колонок и аксессуаров',
                'hero-title3': 'Эксперты по промышленным насосам и расходомерам',
                'hero-desc3': 'Профессиональный поставщик промышленных насосов и расходомеров',
                'view-products': 'Посмотреть продукты',
                'hot-products': 'Популярные продукты',
                'product-categories': 'Категории продуктов',
                'featured-products': 'Рекомендуемые продукты',
                'our-advantages': 'Наши преимущества',
                'high-quality': 'Высокое качество',
                'quality-desc': 'Мы предоставляем высококачественную продукцию, соответствующую международным стандартам',
                'professional-service': 'Профессиональное обслуживание',
                'service-desc': 'Профессиональная предпродажная консультация и сервисная команда',
                'fast-delivery': 'Быстрая доставка',
                'delivery-desc': 'Эффективная логистическая система обеспечивает быструю доставку',
                'technical-support': 'Техническая поддержка',
                'support-desc': 'Комплексная техническая поддержка и решения',
                
                // LC型流量计推荐
                'lc-flowmeter-title': 'Расходомер типа LC',
                'lc-flowmeter-desc': 'Высокоточный расходомер типа LC, подходит для различных промышленных измерений жидкостей. Использует передовые технологии для обеспечения точности и стабильности измерений.',
                'feature1': 'Высокоточное измерение',
                'feature2': 'Коррозионностойкий материал',
                'feature3': 'Простой монтаж и обслуживание',
                'feature4': 'Доступно несколько спецификаций',
                'urgent-delivery': 'Срочная доставка',
                'delivery-warning': '⚠️ Срочная доставка, рекомендуем раннее бронирование',
                'view-details': 'Подробнее',
                
                // 页脚
                'contact-info': 'Контактная информация',
                'company-name1': 'LUIANG PARTS LIANYUNGANG CO.,LTD',
                'address1': 'Адрес: Цзянсу, уезд Гуаньюнь, площадь Ифань, здание 1. 222200',
                'company-name2': 'LUIANG PARTS CO.,LTD',
                'address2': 'Адрес: Шанхай, Линшань, дорога 958, здание 5',
                'quick-links': 'Быстрые ссылки',
                'all-rights-reserved': 'Все права защищены',
                
                // 产品页面
                'products-desc': 'Исследуйте наши высококачественные линии промышленного оборудования',
                'filter-by-category': 'Фильтр по категории:',
                'all-categories': 'Все категории',
                'sort-by': 'Сортировать по:',
                'sort-name': 'По названию',
                'sort-price-low': 'Цена: от низкой к высокой',
                'sort-price-high': 'Цена: от высокой к низкой',
                'load-more': 'Загрузить еще',
                'need-help': 'Нужна помощь с продуктом?',
                'inquiry-desc': 'Наша экспертная команда готова предоставить профессиональную консультацию по продуктам и техническую поддержку',
                'contact-expert': 'Связаться с экспертом',
                
                // 产品详情页面
                'sku': 'Артикул:',
                'in-stock': 'В наличии',
                'product-features': 'Особенности продукта',
                'specifications': 'Технические характеристики',
                'quantity': 'Количество:',
                'request-quote': 'Запросить цену',
                'delivery-time': 'Примерное время доставки: 2-4 недели',
                'product-description': 'Описание продукта',
                'detailed-specs': 'Подробные характеристики',
                'applications': 'Области применения',
                'downloads': 'Загрузки',
                'product-overview': 'Обзор продукта',
                'key-features': 'Ключевые особенности',
                'technical-specs': 'Технические характеристики',
                'application-areas': 'Области применения',
                'download-resources': 'Ресурсы для загрузки',
                'related-products': 'Связанные продукты',
                'feature-high-precision': 'Высокоточное измерение, погрешность менее ±0.5%',
                'feature-corrosion-resistant': 'Коррозионностойкий материал, длительный срок службы',
                'feature-easy-installation': 'Простой монтаж и обслуживание',
                'feature-multiple-specs': 'Доступно несколько спецификаций для удовлетворения различных потребностей',
                'spec-material': 'Материал',
                'spec-accuracy': 'Точность',
                'spec-pressure': 'Рабочее давление',
                'spec-temperature': 'Рабочая температура',
                'spec-model': 'Модель',
                'spec-measurement': 'Диапазон измерений',
                'spec-accuracy': 'Класс точности',
                'spec-pressure-rating': 'Класс давления',
                'spec-parameter': 'Параметр',
                'spec-value': 'Значение',
                'feature1-detail': 'Высокоточное измерение, соответствует строгим промышленным стандартам',
                'feature2-detail': 'Широкий диапазон измерений, адаптируется к разным диапазонам расхода',
                'feature3-detail': 'Доступно несколько выходных сигналов',
                'feature4-detail': 'Степень защиты IP67, подходит для суровых условий',
                'app-petrochemical': 'Нефтехимическая промышленность',
                'app-water-treatment': 'Системы водоподготовки',
                'app-food-beverage': 'Пищевая промышленность',
                'app-pharmaceutical': 'Фармацевтическая промышленность',
                'app-chemical': 'Химическая промышленность',
                'download-catalog': 'Скачать каталог продукции',
                'download-certificate': 'Скачать сертификаты',
                'download-manual': 'Скачать руководство по установке',
                
                // 关于我们页面
                'about-us': 'О нас',
                'about-desc': 'Профессиональный поставщик промышленного оборудования, стремящийся предоставлять качественную продукцию и услуги',
                'welcome-to-luiang': 'Добро пожаловать в LUIANG MACHINE',
                'company-intro-1': 'LUIANG PARTS LIANYUNGANG CO.,LTD - профессиональный поставщик промышленного оборудования, специализирующийся на разработке, производстве и продаже топливораздаточных колонок, промышленных насосов, расходомеров и сопутствующих аксессуаров.',
                'company-intro-2': 'Имея многолетний опыт работы в отрасли, мы стремимся предоставлять глобальным клиентам высококачественные, надежные решения в области промышленного оборудования. Наша продукция широко используется в нефтехимической, водоподготовки, пищевой и других отраслях.',
                'company-intro-3': 'Благодаря постоянным технологическим инновациям и строгому контролю качества мы гарантируем, что каждый продукт соответствует международным стандартам и удовлетворяет разнообразные потребности клиентов.',
                'company-building-alt': 'Здание компании',
                'our-journey': 'Наш путь',
                'timeline-2010-title': 'Основание компании',
                'timeline-2010-desc': 'Основана в Ляньюньгане, начала специализироваться на торговле промышленным оборудованием',
                'timeline-2015-title': 'Расширение бизнеса',
                'timeline-2015-desc': 'Открыла филиал в Шанхае для расширения сферы деятельности',
                'timeline-2018-title': 'Модернизация продукции',
                'timeline-2018-desc': 'Внедрила передовые производственные линии для улучшения качества продукции',
                'timeline-2023-title': 'Международное развитие',
                'timeline-2023-desc': 'Продукция экспортируется в несколько стран, установлены международные партнерские отношения',
                'our-values': 'Наши ценности',
                'value-quality': 'Качество прежде всего',
                'value-quality-desc': 'Мы всегда придерживаемся принципа качества прежде всего, гарантируя, что каждый продукт соответствует высочайшим стандартам',
                'value-innovation': 'Постоянные инновации',
                'value-innovation-desc': 'Постоянно разрабатываем новые технологии и выпускаем новые продукты, отвечающие требованиям рынка',
                'value-customer': 'Клиент прежде всего',
                'value-customer-desc': 'Ориентируемся на потребности клиентов, предоставляя индивидуальные решения',
                'value-integrity': 'Честное ведение бизнеса',
                'value-integrity-desc': 'Соблюдаем принципы честности и устанавливаем долгосрочные стабильные партнерские отношения',
                'our-team': 'Наша команда',
                'team-member-1': 'Инженер Чжан',
                'position-1': 'Технический директор',
                'member-desc-1': '15 лет опыта работы с промышленным оборудованием, специализируется на разработке продукции и технологических инновациях',
                'team-member-2': 'Менеджер Ли',
                'position-2': 'Менеджер по продажам',
                'member-desc-2': '10 лет опыта международной торговли, владеет несколькими языками',
                'team-member-3': 'Супервайзер Ван',
                'position-3': 'Руководитель службы поддержки клиентов',
                'member-desc-3': '8 лет опыта работы в обслуживании клиентов, предоставляет профессиональную техническую поддержку',
                'certifications': 'Сертификаты',
                'cert-iso': 'Сертификат системы качества ISO9001',
                'cert-ce': 'Сертификат CE',
                'cert-patent': 'Множество патентов на продукцию',
                
                // 博客页面
                'blog': 'Блог',
                'blog-desc': 'Отраслевые новости, технические статьи и обновления компании',
                'post-date': 'Дата публикации',
                'category-technical': 'Технические статьи',
                'category-technology': 'Технологический фронт',
                'category-news': 'Новости компании',
                'category-guide': 'Руководство по покупке',
                'blog-title-1': 'Руководство по ежедневному обслуживанию и уходу за промышленными насосами',
                'blog-excerpt-1': 'Промышленные насосы - важное промышленное оборудование, правильное обслуживание может значительно продлить срок их службы. В этой статье подробно описываются ежедневная проверка, регулярное обслуживание и методы устранения распространенных неисправностей...',
                'blog-title-2': 'Последние тенденции развития технологии расходомеров',
                'blog-excerpt-2': 'С развитием Индустрии 4.0 технология расходомеров также постоянно развивается. Новые технологии, такие как умные расходомеры, беспроводная передача и анализ больших данных, меняют традиционные методы измерения расхода...',
                'blog-title-3': 'LUIANG MACHINE участвует в Международной выставке промышленного оборудования 2024',
                'blog-excerpt-3': 'Мы с гордостью участвуем в Международной выставке промышленного оборудования 2024, демонстрируя последние расходомеры типа LC и решения для умных топливораздаточных колонок, получая внимание и похвалу многих клиентов...',
                'blog-title-4': 'Как выбрать подходящий промышленный расходомер',
                'blog-excerpt-4': 'Выбор подходящего промышленного расходомера требует учета нескольких факторов, включая характеристики среды, диапазон расхода, требования к точности, условия установки и т.д. В этой статье представлено подробное руководство по покупке...',
                'read-more': 'Читать далее',
                'search-blog': 'Поиск в блоге',
                'search-placeholder': 'Введите ключевые слова...',
                'search': 'Поиск',
                'categories': 'Категории',
                'category-all': 'Все статьи',
                'popular-posts': 'Популярные статьи',
                'popular-post-1': 'Распространенные неисправности промышленных насосов и решения',
                'popular-post-2': 'Рекомендации по установке расходомеров',
                'popular-post-3': 'График обслуживания топливораздаточных колонок',
                'tags': 'Теги',
                'tag-pump': 'Промышленный насос',
                'tag-flowmeter': 'Расходомер',
                'tag-dispenser': 'Топливораздаточная колонка',
                'tag-maintenance': 'Обслуживание',
                'tag-technology': 'Технология',
                'tag-installation': 'Установка',
                'next-page': 'Следующая страница',
                
                // 联系页面
                'contact-us': 'Контакты',
                'contact-desc': 'Мы всегда готовы предоставить профессиональную консультацию и обслуживание',
                'phone': 'Телефон',
                'email': 'Электронная почта',
                'send-message': 'Отправить сообщение',
                'form-name': 'Имя *',
                'form-company': 'Название компании',
                'form-email': 'Электронная почта *',
                'form-phone': 'Телефон',
                'form-subject': 'Тема *',
                'form-message': 'Содержание сообщения *',
                'select-subject': 'Выберите тему обращения',
                'subject-product': 'Консультация по продукции',
                'subject-quotation': 'Запрос цены',
                'subject-technical': 'Техническая поддержка',
                'subject-partnership': 'Консультация по сотрудничеству',
                'subject-other': 'Другое',
                'message-placeholder': 'Пожалуйста, подробно опишите ваши потребности...',
                'our-location': 'Наше местоположение',
                'map-loading': 'Загрузка карты...',
                'map-desc': 'Местоположение LUIANG PARTS LIANYUNGANG CO.,LTD',
                'visit-us': 'Руководство по посещению',
                'visit-desc': 'Добро пожаловать на посещение и осмотр, мы предоставляем профессиональный показ оборудования и технические консультации.',
                'business-hours': 'Часы работы',
                'hours-weekdays': 'Понедельник-Пятница: 8:30-17:30',
                'hours-saturday': 'Суббота: 9:00-12:00',
                'hours-sunday': 'Воскресенье: Выходной',
                'faq': 'Часто задаваемые вопросы',
                'faq-1-question': 'Как получить коммерческое предложение на продукцию?',
                'faq-1-answer': 'Вы можете отправить запрос через нашу страницу контактов или написать напрямую на электронную почту luiangparts@luiangparts.com, мы предоставим вам подробное коммерческое предложение в кратчайшие сроки.',
                'faq-2-question': 'Каков срок поставки продукции?',
                'faq-2-answer': 'Стандартный срок поставки продукции составляет 2-4 недели, конкретное время зависит от модели продукции и объема заказа. Срочные заказы могут быть обсуждены для ускоренной обработки.',
                'faq-3-question': 'Предоставляется ли техническая поддержка?',
                'faq-3-answer': 'Да, мы предоставляем комплексные услуги технической поддержки, включая руководство по установке продукции, обучение использованию и устранение неисправностей.',
                'faq-4-question': 'Какие способы оплаты поддерживаются?',
                'faq-4-answer': 'Мы поддерживаем банковский перевод TT, аккредитив и другие способы оплаты, конкретные условия могут быть обсуждены в соответствии с потребностями клиента.',
                
                // 页面标题
                'page-title-home': 'LUIANG MACHINE - Профессиональный поставщик промышленного оборудования',
                'page-title-products': 'Продукты - LUIANG MACHINE',
                'page-title-about': 'О нас - LUIANG MACHINE',
                'page-title-blog': 'Блог - LUIANG MACHINE',
                'page-title-contact': 'Контакты - LUIANG MACHINE'
            },
            'vi': {
                // 通用导航
                'home': 'Trang Chủ',
                'about': 'Về Chúng Tôi',
                'products': 'Sản Phẩm',
                'blog': 'Blog',
                'contact': 'Liên Hệ',
                
                // 产品分类
                'fuel-dispenser': 'Máy Bơm Xăng',
                'fuel-dispenser-parts': 'Phụ Tùng Máy Bơm Xăng',
                'adblue-equipment': 'Thiết Bị Adblue',
                'industrial-pump': 'Máy Bơm Công Nghiệp & Đồng Hồ Lưu Lượng',
                'lpg-equipment': 'Thiết Bị LPG',
                'other-equipment': 'Thiết Bị Khác',
                
                // 购物车
                'shopping-cart': 'Giỏ Hàng',
                'request-quotation': 'Yêu Cầu Báo Giá',
                'add-to-cart': 'Thêm Vào Giỏ Hàng',
                
                // 首页内容
                'hero-title1': 'Nhà Cung Cấp Thiết Bị Công Nghiệp Chuyên Nghiệp',
                'hero-desc1': 'Cung cấp máy bơm xăng, máy bơm công nghiệp và đồng hồ lưu lượng chất lượng cao',
                'hero-title2': 'Giải Pháp Máy Bơm Xăng Cao Cấp',
                'hero-desc2': 'Cung cấp các model máy bơm xăng và phụ kiện đa dạng',
                'hero-title3': 'Chuyên Gia Máy Bơm & Đồng Hồ Lưu Lượng',
                'hero-desc3': 'Nhà cung cấp chuyên nghiệp máy bơm công nghiệp và đồng hồ lưu lượng',
                'view-products': 'Xem Sản Phẩm',
                'hot-products': 'Sản Phẩm Hot',
                'product-categories': 'Danh Mục Sản Phẩm',
                'featured-products': 'Sản Phẩm Nổi Bật',
                'our-advantages': 'Lợi Thế Của Chúng Tôi',
                'high-quality': 'Chất Lượng Cao',
                'quality-desc': 'Chúng tôi cung cấp các sản phẩm chất lượng cao đáp ứng tiêu chuẩn quốc tế',
                'professional-service': 'Dịch Vụ Chuyên Nghiệp',
                'service-desc': 'Đội ngũ tư vấn trước bán hàng và dịch vụ sau bán hàng chuyên nghiệp',
                'fast-delivery': 'Giao Hàng Nhanh',
                'delivery-desc': 'Hệ thống logistics hiệu quả đảm bảo giao hàng nhanh chóng',
                'technical-support': 'Hỗ Trợ Kỹ Thuật',
                'support-desc': 'Hỗ trợ kỹ thuật toàn diện và giải pháp',
                
                // LC型流量计推荐
                'lc-flowmeter-title': 'Đồng Hồ Lưu Lượng Loại LC',
                'lc-flowmeter-desc': 'Đồng hồ lưu lượng loại LC độ chính xác cao, phù hợp cho các phép đo chất lỏng công nghiệp đa dạng. Sử dụng công nghệ tiên tiến để đảm bảo độ chính xác và ổn định đo lường.',
                'feature1': 'Đo lường độ chính xác cao',
                'feature2': 'Vật liệu chống ăn mòn',
                'feature3': 'Dễ dàng lắp đặt và bảo trì',
                'feature4': 'Nhiều thông số kỹ thuật có sẵn',
                'urgent-delivery': 'Giao Hàng Khẩn',
                'delivery-warning': '⚠️ Giao hàng khẩn, khuyến nghị đặt trước',
                'view-details': 'Xem Chi Tiết',
                
                // 页脚
                'contact-info': 'Thông Tin Liên Hệ',
                'company-name1': 'LUIANG PARTS LIANYUNGANG CO.,LTD',
                'address1': 'Địa chỉ: Tòa nhà số 1, Quảng trường Yifan, Huyện Guanyun, Giang Tô, Trung Quốc. 222200',
                'company-name2': 'LUIANG PARTS CO.,LTD',
                'address2': 'Địa chỉ: Tòa nhà số 5, Số 958 Đường Lingshan, Thượng Hải, Trung Quốc',
                'quick-links': 'Liên Kết Nhanh',
                'all-rights-reserved': 'Đã đăng ký bản quyền',
                
                // 产品页面
                'products-desc': 'Khám phá các dòng sản phẩm thiết bị công nghiệp chất lượng cao của chúng tôi',
                'filter-by-category': 'Lọc theo danh mục:',
                'all-categories': 'Tất cả danh mục',
                'sort-by': 'Sắp xếp theo:',
                'sort-name': 'Theo tên',
                'sort-price-low': 'Giá: Thấp đến cao',
                'sort-price-high': 'Giá: Cao đến thấp',
                'load-more': 'Tải thêm',
                'need-help': 'Cần trợ giúp về sản phẩm?',
                'inquiry-desc': 'Đội ngũ chuyên gia của chúng tôi sẵn sàng cung cấp tư vấn sản phẩm chuyên nghiệp và hỗ trợ kỹ thuật',
                'contact-expert': 'Liên Hệ Chuyên Gia',
                
                // 产品详情页面
                'sku': 'Mã sản phẩm:',
                'in-stock': 'Còn hàng',
                'product-features': 'Tính năng sản phẩm',
                'specifications': 'Thông số kỹ thuật',
                'quantity': 'Số lượng:',
                'request-quote': 'Yêu Cầu Báo Giá',
                'delivery-time': 'Thời gian giao hàng dự kiến: 2-4 tuần',
                'product-description': 'Mô tả sản phẩm',
                'detailed-specs': 'Thông số chi tiết',
                'applications': 'Lĩnh vực ứng dụng',
                'downloads': 'Tải xuống',
                'product-overview': 'Tổng quan sản phẩm',
                'key-features': 'Tính năng chính',
                'technical-specs': 'Thông số kỹ thuật',
                'application-areas': 'Lĩnh vực ứng dụng',
                'download-resources': 'Tài nguyên tải xuống',
                'related-products': 'Sản phẩm liên quan',
                'feature-high-precision': 'Đo lường độ chính xác cao, sai số dưới ±0.5%',
                'feature-corrosion-resistant': 'Vật liệu chống ăn mòn, tuổi thọ sử dụng lâu dài',
                'feature-easy-installation': 'Dễ dàng lắp đặt và bảo trì',
                'feature-multiple-specs': 'Nhiều thông số kỹ thuật có sẵn để đáp ứng các nhu cầu khác nhau',
                'spec-material': 'Chất liệu',
                'spec-accuracy': 'Độ chính xác',
                'spec-pressure': 'Áp suất làm việc',
                'spec-temperature': 'Nhiệt độ làm việc',
                'spec-model': 'Model',
                'spec-measurement': 'Phạm vi đo',
                'spec-accuracy': 'Cấp chính xác',
                'spec-pressure-rating': 'Cấp áp suất',
                'spec-parameter': 'Thông số',
                'spec-value': 'Giá trị',
                'feature1-detail': 'Đo lường độ chính xác cao, đáp ứng tiêu chuẩn công nghiệp nghiêm ngặt',
                'feature2-detail': 'Tỷ lệ dải đo rộng, thích ứng với các phạm vi lưu lượng khác nhau',
                'feature3-detail': 'Nhiều tín hiệu đầu ra có sẵn',
                'feature4-detail': 'Cấp bảo vệ IP67, phù hợp với môi trường khắc nghiệt',
                'app-petrochemical': 'Công nghiệp hóa dầu',
                'app-water-treatment': 'Hệ thống xử lý nước',
                'app-food-beverage': 'Công nghiệp thực phẩm & đồ uống',
                'app-pharmaceutical': 'Công nghiệp dược phẩm',
                'app-chemical': 'Công nghiệp hóa chất',
                'download-catalog': 'Tải xuống catalog sản phẩm',
                'download-certificate': 'Tải xuống chứng nhận',
                'download-manual': 'Tải xuống hướng dẫn lắp đặt',
                
                // 关于我们页面
                'about-us': 'Về Chúng Tôi',
                'about-desc': 'Nhà cung cấp thiết bị công nghiệp chuyên nghiệp cam kết cung cấp sản phẩm và dịch vụ chất lượng',
                'welcome-to-luiang': 'Chào mừng đến với LUIANG MACHINE',
                'company-intro-1': 'LUIANG PARTS LIANYUNGANG CO.,LTD là nhà cung cấp thiết bị công nghiệp chuyên nghiệp, tập trung vào nghiên cứu phát triển, sản xuất và bán máy bơm xăng, máy bơm công nghiệp, đồng hồ lưu lượng và phụ kiện liên quan.',
                'company-intro-2': 'Với nhiều năm kinh nghiệm trong ngành, chúng tôi cam kết cung cấp cho khách hàng toàn cầu các giải pháp thiết bị công nghiệp chất lượng cao, đáng tin cậy. Sản phẩm của chúng tôi được sử dụng rộng rãi trong hóa dầu, xử lý nước, thực phẩm đồ uống và các ngành công nghiệp khác.',
                'company-intro-3': 'Thông qua đổi mới công nghệ liên tục và kiểm soát chất lượng nghiêm ngặt, chúng tôi đảm bảo mỗi sản phẩm đều đáp ứng tiêu chuẩn quốc tế và thỏa mãn nhu cầu đa dạng của khách hàng.',
                'company-building-alt': 'Tòa nhà công ty',
                'our-journey': 'Hành Trình Của Chúng Tôi',
                'timeline-2010-title': 'Thành lập công ty',
                'timeline-2010-desc': 'Thành lập tại Liên Vân Cảng, bắt đầu tập trung vào thương mại thiết bị công nghiệp',
                'timeline-2015-title': 'Mở rộng kinh doanh',
                'timeline-2015-desc': 'Thành lập chi nhánh tại Thượng Hải để mở rộng phạm vi kinh doanh',
                'timeline-2018-title': 'Nâng cấp sản phẩm',
                'timeline-2018-desc': 'Giới thiệu dây chuyền sản xuất tiên tiến để cải thiện chất lượng sản phẩm',
                'timeline-2023-title': 'Phát triển quốc tế',
                'timeline-2023-desc': 'Sản phẩm xuất khẩu đến nhiều quốc gia, thiết lập quan hệ đối tác quốc tế',
                'our-values': 'Giá Trị Của Chúng Tôi',
                'value-quality': 'Chất Lượng Hàng Đầu',
                'value-quality-desc': 'Chúng tôi luôn tuân thủ nguyên tắc chất lượng hàng đầu, đảm bảo mỗi sản phẩm đều đạt tiêu chuẩn cao nhất',
                'value-innovation': 'Đổi Mới Liên Tục',
                'value-innovation-desc': 'Liên tục phát triển công nghệ mới và ra mắt sản phẩm mới đáp ứng nhu cầu thị trường',
                'value-customer': 'Khách Hàng Là Trên Hết',
                'value-customer-desc': 'Định hướng theo nhu cầu khách hàng, cung cấp giải pháp cá nhân hóa',
                'value-integrity': 'Kinh Doanh Chính Trực',
                'value-integrity-desc': 'Tuân thủ nguyên tắc chính trực và thiết lập mối quan hệ hợp tác ổn định lâu dài',
                'our-team': 'Đội Ngũ Của Chúng Tôi',
                'team-member-1': 'Kỹ Sư Zhang',
                'position-1': 'Giám Đốc Kỹ Thuật',
                'member-desc-1': '15 năm kinh nghiệm thiết bị công nghiệp, tập trung vào nghiên cứu phát triển sản phẩm và đổi mới công nghệ',
                'team-member-2': 'Quản Lý Li',
                'position-2': 'Quản Lý Kinh Doanh',
                'member-desc-2': '10 năm kinh nghiệm thương mại quốc tế, thông thạo nhiều ngôn ngữ',
                'team-member-3': 'Giám Sát Vương',
                'position-3': 'Giám Sát Dịch Vụ Khách Hàng',
                'member-desc-3': '8 năm kinh nghiệm dịch vụ khách hàng, cung cấp hỗ trợ kỹ thuật chuyên nghiệp',
                'certifications': 'Chứng Nhận',
                'cert-iso': 'Chứng Nhận Hệ Thống Chất Lượng ISO9001',
                'cert-ce': 'Chứng Nhận CE',
                'cert-patent': 'Nhiều Bằng Sáng Chế Sản Phẩm',
                
                // 博客页面
                'blog': 'Blog',
                'blog-desc': 'Tin tức ngành, bài viết kỹ thuật và cập nhật công ty',
                'post-date': 'Ngày đăng',
                'category-technical': 'Bài Viết Kỹ Thuật',
                'category-technology': 'Công Nghệ Tiên Phong',
                'category-news': 'Tin Công Ty',
                'category-guide': 'Hướng Dẫn Mua Hàng',
                'blog-title-1': 'Hướng Dẫn Bảo Trì và Bảo Dưỡng Hàng Ngày cho Máy Bơm Công Nghiệp',
                'blog-excerpt-1': 'Máy bơm công nghiệp là thiết bị công nghiệp quan trọng, bảo trì đúng cách có thể kéo dài đáng kể tuổi thọ sử dụng. Bài viết này chi tiết về kiểm tra hàng ngày, bảo trì định kỳ và phương pháp xử lý sự cố thông thường...',
                'blog-title-2': 'Xu Hướng Phát Triển Mới Nhất trong Công Nghệ Đồng Hồ Lưu Lượng',
                'blog-excerpt-2': 'Với sự phát triển của Công nghiệp 4.0, công nghệ đồng hồ lưu lượng cũng không ngừng đổi mới. Các công nghệ mới như đồng hồ lưu lượng thông minh, truyền tải không dây và phân tích dữ liệu lớn đang thay đổi phương pháp đo lưu lượng truyền thống...',
                'blog-title-3': 'LUIANG MACHINE Tham Gia Triển Lãm Thiết Bị Công Nghiệp Quốc Tế 2024',
                'blog-excerpt-3': 'Chúng tôi vinh dự tham gia Triển lãm Thiết bị Công nghiệp Quốc tế 2024, trưng bày các đồng hồ lưu lượng loại LC mới nhất và giải pháp máy bơm xăng thông minh, nhận được sự quan tâm và đánh giá cao từ nhiều khách hàng...',
                'blog-title-4': 'Cách Chọn Đồng Hồ Lưu Lượng Công Nghiệp Phù Hợp',
                'blog-excerpt-4': 'Chọn đồng hồ lưu lượng công nghiệp phù hợp cần xem xét nhiều yếu tố, bao gồm đặc tính môi trường, phạm vi lưu lượng, yêu cầu độ chính xác, môi trường lắp đặt, v.v. Bài viết này cung cấp hướng dẫn mua hàng chi tiết...',
                'read-more': 'Đọc Thêm',
                'search-blog': 'Tìm Kiếm Blog',
                'search-placeholder': 'Nhập từ khóa...',
                'search': 'Tìm Kiếm',
                'categories': 'Danh Mục',
                'category-all': 'Tất Cả Bài Viết',
                'popular-posts': 'Bài Viết Phổ Biến',
                'popular-post-1': 'Sự Cố Thường Gặp của Máy Bơm Công Nghiệp và Giải Pháp',
                'popular-post-2': 'Lưu Ý Khi Lắp Đặt Đồng Hồ Lưu Lượng',
                'popular-post-3': 'Lịch Bảo Trì Máy Bơm Xăng',
                'tags': 'Thẻ',
                'tag-pump': 'Máy Bơm Công Nghiệp',
                'tag-flowmeter': 'Đồng Hồ Lưu Lượng',
                'tag-dispenser': 'Máy Bơm Xăng',
                'tag-maintenance': 'Bảo Trì',
                'tag-technology': 'Công Nghệ',
                'tag-installation': 'Lắp Đặt',
                'next-page': 'Trang Tiếp Theo',
                
                // 联系页面
                'contact-us': 'Liên Hệ',
                'contact-desc': 'Chúng tôi luôn sẵn sàng cung cấp tư vấn và dịch vụ chuyên nghiệp',
                'phone': 'Điện Thoại',
                'email': 'Email',
                'send-message': 'Gửi Tin Nhắn',
                'form-name': 'Tên *',
                'form-company': 'Tên Công Ty',
                'form-email': 'Email *',
                'form-phone': 'Điện Thoại',
                'form-subject': 'Chủ Đề *',
                'form-message': 'Nội Dung Tin Nhắn *',
                'select-subject': 'Chọn chủ đề tư vấn',
                'subject-product': 'Tư Vấn Sản Phẩm',
                'subject-quotation': 'Yêu Cầu Báo Giá',
                'subject-technical': 'Hỗ Trợ Kỹ Thuật',
                'subject-partnership': 'Tư Vấn Hợp Tác',
                'subject-other': 'Khác',
                'message-placeholder': 'Vui lòng mô tả chi tiết nhu cầu của bạn...',
                'our-location': 'Vị Trí Của Chúng Tôi',
                'map-loading': 'Đang tải bản đồ...',
                'map-desc': 'Vị trí LUIANG PARTS LIANYUNGANG CO.,LTD',
                'visit-us': 'Hướng Dẫn Tham Quan',
                'visit-desc': 'Chào mừng bạn đến tham quan và kiểm tra, chúng tôi cung cấp dịch vụ trưng bày thiết bị chuyên nghiệp và giải thích kỹ thuật.',
                'business-hours': 'Giờ Làm Việc',
                'hours-weekdays': 'Thứ Hai-Thứ Sáu: 8:30-17:30',
                'hours-saturday': 'Thứ Bảy: 9:00-12:00',
                'hours-sunday': 'Chủ Nhật: Nghỉ',
                'faq': 'Câu Hỏi Thường Gặp',
                'faq-1-question': 'Làm thế nào để nhận báo giá sản phẩm?',
                'faq-1-answer': 'Bạn có thể gửi yêu cầu báo giá qua trang liên hệ của chúng tôi, hoặc gửi email trực tiếp đến luiangparts@luiangparts.com, chúng tôi sẽ cung cấp báo giá chi tiết cho bạn trong thời gian sớm nhất.',
                'faq-2-question': 'Thời gian giao hàng sản phẩm là bao lâu?',
                'faq-2-answer': 'Thời gian giao hàng tiêu chuẩn là 2-4 tuần, thời gian cụ thể phụ thuộc vào model sản phẩm và số lượng đơn hàng. Đơn hàng khẩn có thể thương lượng xử lý nhanh.',
                'faq-3-question': 'Có cung cấp hỗ trợ kỹ thuật không?',
                'faq-3-answer': 'Có, chúng tôi cung cấp dịch vụ hỗ trợ kỹ thuật toàn diện, bao gồm hướng dẫn lắp đặt sản phẩm, đào tạo sử dụng và xử lý sự cố.',
                'faq-4-question': 'Hỗ trợ những phương thức thanh toán nào?',
                'faq-4-answer': 'Chúng tôi hỗ trợ chuyển khoản TT, thư tín dụng và các phương thức thanh toán khác, cụ thể có thể thương lượng theo nhu cầu khách hàng.',
                
                // 页面标题
                'page-title-home': 'LUIANG MACHINE - Nhà Cung Cấp Thiết Bị Công Nghiệp Chuyên Nghiệp',
                'page-title-products': 'Sản Phẩm - LUIANG MACHINE',
                'page-title-about': 'Về Chúng Tôi - LUIANG MACHINE',
                'page-title-blog': 'Blog - LUIANG MACHINE',
                'page-title-contact': 'Liên Hệ - LUIANG MACHINE'
            }
        };
    }
    
    applyLanguage(lang) {
        this.currentLang = lang;
        localStorage.setItem('selectedLanguage', lang);
        
        // 更新语言选择器
        const languageSelect = document.getElementById('language-select');
        if (languageSelect) {
            languageSelect.value = lang;
        }
        
        // 更新所有带有data-lang属性的元素
        const elements = document.querySelectorAll('[data-lang]');
        elements.forEach(element => {
            const key = element.getAttribute('data-lang');
            if (this.translations[lang] && this.translations[lang][key]) {
                element.textContent = this.translations[lang][key];
            }
        });
        
        // 更新页面标题
        this.updatePageTitle();
    }
    
    updatePageTitle() {
        const pageTitle = document.querySelector('title');
        if (!pageTitle) return;
        
        const path = window.location.pathname;
        let pageKey = 'page-title-home';
        
        if (path.includes('products.html')) pageKey = 'page-title-products';
        else if (path.includes('about.html')) pageKey = 'page-title-about';
        else if (path.includes('blog.html')) pageKey = 'page-title-blog';
        else if (path.includes('contact.html')) pageKey = 'page-title-contact';
        
        if (this.translations[this.currentLang] && this.translations[this.currentLang][pageKey]) {
            pageTitle.textContent = this.translations[this.currentLang][pageKey];
        }
    }
    
    setupLanguageSelector() {
        const languageSelect = document.getElementById('language-select');
        if (languageSelect) {
            languageSelect.addEventListener('change', (e) => {
                this.applyLanguage(e.target.value);
            });
        }
    }
    
    getTranslation(key) {
        return this.translations[this.currentLang] && this.translations[this.currentLang][key] 
            ? this.translations[this.currentLang][key] 
            : key;
    }
}

// 初始化语言系统
const languageSystem = new LanguageSystem();